# Generated by Django 5.1.1 on 2024-10-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0008_rename_website_url_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
