# Generated by Django 5.1.1 on 2024-10-14 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0010_profile1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile1',
        ),
    ]
